### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by karldreher** [karldreher/SubredditExchange#1]
A simple dockerfile is desired for this project, to allow Docker as a useful (and preferred) build target.

Like some of my [other projects](https://github.com/karldreher/KnowYourPorts/blob/master/Dockerfile) this should use the python:3-alpine base image.

**Comment by amitkumarj441** [comment]
@karldreher Please create a folder "redditapp" and move you `.py` file there to serve as I created a dockerfile for it and let's create a issue for `requirements.txt` file for reddit app.

P.S.: I have added the Dockerfile #4 and once you run this it creates `redditapp` directory.

**Comment by karldreher** [comment]
Hi @amitkumarj441 , I'm not sure this is exactly what I'm looking for.  If you click the link above https://github.com/karldreher/KnowYourPorts/blob/master/Dockerfile, that is pretty much all that I think is required right now.  The dockerfile for this project could be truly, almost identical to that one.  I'm going to close your PR, if you'd like to submit a new one that is a little simpler that would be fine.

**Comment by karldreher** [comment]
@danielpops , you the man!  thanks.
