### ISSUE TITLE
Segregate secrets from app

### ISSUE THREAD

**Issue by karldreher** [karldreher/SubredditExchange#2]
The following should not be hard coded in the app as it currently is.  

app_client_id=''
app_client_secret=''

Could be in the form of a separate file, or a python import.
Removing this will aid future contribution, so that contributors can obtain their own id and secret to speed their development.

Ideally a skeleton file should be added to the repo, but then added to gitignore as well to prevent key disclosure.  Should be well commented so developers know how to interact with the file.

**Comment by theparadoxer02** [comment]
i want to work on this issue.May i ?

**Comment by karldreher** [comment]
Hi @theparadoxer02 , @notderw beat you to this, I'd like to move forward with their suggestion.  I would really value your contribution in the future.

**Comment by karldreher** [comment]
Merged from #8 , thanks to @notderw !
